# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JRTAPIModel' do
pod 'JSONModel'
pod 'AFNetworking'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configuration_list.set_setting('HEADER_SEARCH_PATHS', '')
    end
end